version: "3"

services:
  v2ray:
    image: ghcr.io/getimages/v2fly-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "127.0.0.1:1010:1010"
      - "127.0.0.1:1010:1010/udp"
      - "127.0.0.1:1110:1110"
      - "3389:3389"
      - "3389:3389/udp"
      - "443:443"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
