version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db_name
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: example_db_user
      WORDPRESS_DB_PASSWORD: example_db_password
      WORDPRESS_DB_NAME: example_db_name
    volumes:
      - wordpress:/var/www/html

volumes:
  db_data:
  wordpress:

