version: '3'

services:
  mikrotik:
    image: evilfreelancer/docker-routeros:6.42.12
    ports:
      - "8291:8291"
      - "4443:443"
      - "1723:1723"
      - "1701:1701/udp"
      - "4500:4500/udp"
      - "47:47/udp"
      - "8080:8080"
    volumes:
      - mikrotik-data:/mikrotik-data

volumes:
  mikrotik-data:
