version: '3.9'

services:

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default_html/:/var/www/default/:ro
    ports:
      - "80:80"

