version: '3.9'

services:

  db1:
    image: mysql:5.7
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: your_wordpress_password

  redis1:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass your-redis-password-here --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    volumes:
      - redis1_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  wp1:
    depends_on:
      - wordpress1
    image: wordpress:latest
    volumes:
      - wordpress1_content:/var/www/html/
      - ./htaccess:/var/www/html/.htaccess:ro
      - ./google0f1ec02adaf8b2e0.html:/var/www/html/google0f1ec02adaf8b2e0.html:ro
    restart: always

  wordpress1:
    depends_on:
      - db1
      - redis1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wordpress1_content:/var/www/html/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: your_wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis configuration */
        define('WP_REDIS_HOST', 'redis1');
        define('WP_REDIS_PORT', '6379');
        define('WP_REDIS_PASSWORD', 'your-redis-password-here');
        define('WP_CACHE_KEY_SALT', 'your-unique-salt-here');
        define('WP_CACHE', true);
        define('DISALLOW_FILE_EDIT', true);
      REDIS_HOST: redis1

  php1:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html:ro
      - ./php.ini:/usr/local/etc/php/php.ini:ro

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - wp1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default_html/:/var/www/default/:ro
    ports:
      - "80:80"

volumes:
  db1_data:
  wordpress1_content:
  redis1_data:

